### ISSUE TITLE
Support for watchOS

### ISSUE THREAD

**Issue by johanan1** [Romixery/SwiftStomp#13]
Any plans for supporting WatchOS?

**Comment by Romixery** [comment]
Hi, At the current time now. But in the future, I'll consider it.

**Comment by francescopedronomnys** [comment]
If anyone is interested [these changes](https://github.com/Romixery/SwiftStomp/compare/master...francescopedronomnys:SwiftStomp:watchOs_support) allow the package to be compiled on watchOS, anyway see [Low-level networking on watchOS](https://developer.apple.com/documentation/technotes/tn3135-low-level-networking-on-watchos) for limitations on WebSockets on watchOS, so my code changes are untested because my use case is not allowed.
